// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import RemovalsController from "./removals_controller"

import MapController from "../../components/map_component_controller"
application.register("map-component", MapController)
application.register("removals", RemovalsController)
